[package]
name = "serpent-cli"
version = "0.1.0"
authors = ["Henri Lunnikivi <henri.lunnikivi@gmail.com>"]
edition = "2018"

[[bin]]
name = "serpent"
path = "src/main.rs"

[dependencies]
serpent = { path = "../serpent" }
clap = "^2.33"
thiserror = "^1.0"
anyhow = "^1.0"
# Must match with rustc_ast version in serpent: "673.0.0"
rustc-ap-rustc_span = "673.0.0"
itertools = "0.9.0"
